### ISSUE TITLE
Bug: 博客文章内生成的引用链接有问题

### ISSUE THREAD

**Issue by char8x** [tisonkun/tisonkun.github.io#38]
## 问题
文章中的引用链接好像指向的是相对位置，页面会 404
<img width="871" alt="image" src="https://user-images.githubusercontent.com/6831013/189490940-5a9de865-b3ed-4748-a350-4477f4792ca1.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/6831013/189490984-d7ad7f02-ec7a-4093-80c0-85cb0249dc93.png">

**Comment by tisonkun** [comment]
我还是第一次看到这个问题。

cc @stevenjoezhang 这是 Hexo/NexT 的预期行为吗？相对链接主要如果在 GitHub 打开也能正常渲染。不然 post 之间互相引用的最佳实践是什么呢？

**Comment by tisonkun** [comment]
我换成 [`{% post_link %}`](https://hexo.io/docs/tag-plugins.html#Include-Posts) 解决了，你可以再试试。

**Comment by stevenjoezhang** [comment]
这个链接可能会出现在两个位置：博客首页的文章摘要中，或者文章本身的页面中。写相对链接的话就会出问题。`post_link` 或者手动写一个绝对链接都可以。前者的好处是链接的文章 URL 改变了也会自动更新。

**Comment by tisonkun** [comment]
嗯，我写 post_link 吧，一个是自动更新，另一个是也能明显跟 markdown 的语法区分开来。如果有比较稳定的办法 resolve 相对路径，好处就是我在阅读 markdown 文件（而不是通过博客网站）的时候，也能正常跳转。
